//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by Rafael Ferreira on 7/13/16.
//  Copyright (c) 2016 Swift Yah. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderInteractorInput {
	var shippingMethods: [String] { get }

	func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request)
}

protocol CreateOrderInteractorOutput {
	func presentExpirationDate(response: CreateOrder_FormatExpirationDate_Response)
}

class CreateOrderInteractor: CreateOrderInteractorInput {
	var output: CreateOrderInteractorOutput!
	var worker: CreateOrderWorker!
	var shippingMethods: [String] = [
		"Standard Shipping",
		"Two-Day Shipping",
		"One-Day Shipping"
	]

	// MARK: Business logic

	func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request) {
		let response = CreateOrder_FormatExpirationDate_Response(date: request.date)

		output.presentExpirationDate(response)
	}
}
