//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Rafael Ferreira on 7/13/16.
//  Copyright (c) 2016 Swift Yah. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateOrder_FormatExpirationDate_Request {
	var date: NSDate
}

struct CreateOrder_FormatExpirationDate_Response {
	var date: NSDate
}

struct CreateOrder_FormatExpirationDate_ViewModel {
	var date: String
}
